In [1]:
# added path
import sys
import os

sys.path.append(os.path.abspath('..'))

In [2]:
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
from gpg.preprocess import Preprocess

In [4]:
# load ply
pcd = o3d.io.read_point_cloud('../data/desk_topview.ply')

In [5]:
o3d.visualization.draw_geometries([pcd])

In [6]:
# preprocess
preprocess = Preprocess()
preprocessed_pcd, removed_indices = preprocess(pcd)

In [11]:
o3d.visualization.draw_geometries([preprocessed_pcd])

In [13]:
# vertex normal estimation
preprocessed_pcd.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30)
)

In [14]:
# To display normals, type n key. Normals gets shorten by type - key
o3d.visualization.draw_geometries([preprocessed_pcd])

In [15]:
print('Print a normal vector of the 0th point')
print(preprocessed_pcd.normals[0])

Print a normal vector of the 0th point
[-0.3973446   0.33685403  0.85360801]


In [21]:
# convert normals to numpy
import numpy as np
print('Print the normal vectors of the first 10 points')
print(np.asarray(preprocessed_pcd.normals)[:10, :])

Print the normal vectors of the first 10 points
[[-0.3973446   0.33685403  0.85360801]
 [-0.41516614  0.32541654  0.8495535 ]
 [-0.44485564  0.26669588  0.85497179]
 [-0.38808797  0.23084866  0.89224247]
 [-0.11097698  0.00424373  0.99381392]
 [-0.03304845 -0.04470374  0.99845349]
 [ 0.03891919 -0.05651887  0.99764268]
 [ 0.05551362 -0.05321337  0.9970389 ]
 [ 0.08708094 -0.01116027  0.99613872]
 [-0.31609339  0.06078867  0.94677859]]


In [22]:
# crop point cloud
demo_crop_data = o3d.data.DemoCropPointCloud()
pcd = o3d.io.read_point_cloud(demo_crop_data.point_cloud_path)

[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/DemoCropPointCloud.zip
[Open3D INFO] Downloaded to /home/harumo/open3d_data/download/DemoCropPointCloud/DemoCropPointCloud.zip
[Open3D INFO] Created directory /home/harumo/open3d_data/extract/DemoCropPointCloud.
[Open3D INFO] Extracting /home/harumo/open3d_data/download/DemoCropPointCloud/DemoCropPointCloud.zip.
[Open3D INFO] Extracted to /home/harumo/open3d_data/extract/DemoCropPointCloud.


In [25]:
vol = o3d.visualization.read_selection_polygon_volume(demo_crop_data.cropped_json_path)

In [26]:
chair = vol.crop_point_cloud(pcd)

In [29]:
o3d.visualization.draw_geometries([pcd])

In [ ]:
dists = pcd.compute_point_cloud_distance(chair)